[package]
name = "rust-project-template"
version = "0.1.0"
authors = ["Cassandra Pearson <cnegrich@gmail.com>"]
edition = "2021"

[dependencies]
anyhow = "1.0.94"
CrypticRust = { git = "https://github.com/cassiepearson/CrypticRust.git"}